config/routes.rb
ThinkPic::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get 'sign_in', :to => 'pics#index', :as => :new_user_session
    get 'sign_out', :to => 'users/omniauth_callbacks#destroy', :as => :sign_out
  end
  resources :users, :only => [:index, :destroy]
  resources :pics do
    collection do
      get 'list'
    end
  end
  get 'tags/:tag', to: 'pics#pics_by_tags', as: :tag
  get 'user/:username', to: 'pics#userpics', as: :userpics
  get 'likeit/:id', to: 'pics#likeit', as: :likeit

  root :to => 'pics#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/like.rb
class Like < ActiveRecord::Base
  attr_accessible :pic_id, :user_id
  belongs_to :user
  belongs_to :pic
end

app/models/pic.rb
class Pic < ActiveRecord::Base
	belongs_to :user
  has_many :likes
  belongs_to :pic_style
	attr_accessible :main, :bold, :tag_list, :pic_style_id
  acts_as_taggable_on :tags
  default_scope order("created_at DESC")
end

app/models/pic_style.rb
class PicStyle < ActiveRecord::Base
  attr_accessible :main_color, :bold_color, :bg, :name
  has_attached_file :bg
  has_many :pic

  def to_js
  	{
  		"main_color" => main_color,
  		"bold_color" => bold_color,
  		"bg" => bg.url
  	}
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :nickname, :provider, :url, :username

  has_many :pics, dependent: :destroy
  has_one :like, through: :pic
  
  def self.find_for_facebook_oauth access_token
    if user = User.where(:url => access_token.info.urls.Facebook).first
      user
    else 
      User.create!(:provider => access_token.provider, :url => access_token.info.urls.Facebook, :username => access_token.extra.raw_info.name, :nickname => access_token.extra.raw_info.username, :email => access_token.extra.raw_info.email, :password => Devise.friendly_token[0,20]) 
    end
  end

  def self.find_for_vkontakte_oauth access_token
    p access_token
    if user = User.where(:url => access_token.info.urls.Vkontakte).first
      user
    else 
      User.create!(:provider => access_token.provider, :url => access_token.info.urls.Vkontakte, :username => access_token.info.name, :nickname => access_token.extra.raw_info.uid, :email => access_token.extra.raw_info.uid.to_s+'@vk.com', :password => Devise.friendly_token[0,20]) 
    end
  end

end

app/controllers/application_controller.rb
# encoding: utf-8

class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :sign_out_if_banned



  private


    def sign_out_if_banned
      if user_signed_in?
        if current_user.banned == true
          sign_out(:user)
          flash[:error] = "Уважаемый пользователь, поздравляем тебя с баном! Скажи привет френдзоне или напиши в техническую поддержку. Вопросы типа WTF, не принимаются."
          redirect_to root_path
        end
      end
    end

end

app/controllers/pics_controller.rb
class PicsController < ApplicationController

  before_filter :authenticate_user!, :only => [:new, :create, :destroy]
  require 'will_paginate/array'

	def index
	  @pics = Pic.all.find_all{|x| x.likes.count >= 5}.paginate(:page => params[:page], :per_page => 10)
	end

    def list
	  @pics = Pic.find(:all, order:"created_at DESC").paginate(:page => params[:page], :per_page => 10)
	end


	def new
		@pic = Pic.new
        @pic_style = PicStyle.find_by_id (params[:style] || 1)
        respond_to do |format|
          format.html # index.html.erb
          format.json {render json: @pic_style.to_js}
        end
	end

	def create
		@pic = Pic.new(params[:pic])
        @pic.user = current_user
		respond_to do |format|
			if @pic.save
				format.html{redirect_to pic_path(@pic)}
			else
				render action: "new"
			end
		end
	end

    def show
        @pic = [] << (Pic.find_by_id params[:id])
    end

    def userpics
        @user = User.find_by_id(params[:username])
        @pics = @user.pics.paginate(:page => params[:page], :per_page => 10)
    end

    def pics_by_tags
        @pics = Pic.tagged_with(params[:tag]).paginate(:page => params[:page], :per_page => 10)
    end

    def likeit
        @pic = Pic.find_by_id params[:id]
        if !(like = @pic.likes.where(user_id: current_user)).blank?
            Like.destroy like
        else
            Like.create(pic_id: @pic.id, user_id: current_user.id)
        end
    end

    def destroy
        pic = Pic.find_by_id params[:id]
        if pic.user == current_user
            pic.destroy
            redirect_to root_path
        else
            redirect_to root_path
            flash[:notice] = "hack"
        end
    end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < ApplicationController
  def facebook
    @user = User.find_for_facebook_oauth request.env["omniauth.auth"]
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
     sign_in_and_redirect @user, :event => :authentication
    else
      flash[:notice] = "authentication error"
      redirect_to root_path
    end
  end

  def vkontakte
    @user = User.find_for_vkontakte_oauth request.env["omniauth.auth"]
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Vkontakte"
      sign_in_and_redirect @user, :event => :authentication
    else
      flash[:notice] = "authentication error"
      redirect_to root_path
    end
  end
  
  def destroy
    sign_out current_user
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/views/layouts/_content.html.haml
%div{ id: "content", class: "grid_8"}
  - if flash[:error]
    #alert-error
      = flash[:error]
    .clear
          
  = yield
    
    

app/views/layouts/_counters.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-7862805-24']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

<!-- Yandex.Metrika counter -->
<script type="text/javascript">
(function (d, w, c) {
    (w[c] = w[c] || []).push(function() {
        try {
            w.yaCounter20382412 = new Ya.Metrika({id:20382412,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true});
        } catch(e) { }
    });

    var n = d.getElementsByTagName("script")[0],
        s = d.createElement("script"),
        f = function () { n.parentNode.insertBefore(s, n); };
    s.type = "text/javascript";
    s.async = true;
    s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

    if (w.opera == "[object Opera]") {
        d.addEventListener("DOMContentLoaded", f, false);
    } else { f(); }
})(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="//mc.yandex.ru/watch/20382412" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

app/views/layouts/_footer.html.haml
.footer
  %div{ class: "container_12"}
    Copyright © 2013 Thinkpic.ru
    %br
    С вопросами и предложениями писать на
    %b one@thinkpic.ru
    %br
    Права на контент принадлежат владельцам аккаунтов
    = render partial: 'layouts/counters'

app/views/layouts/_header.html.haml
.header
    %div{ class: "container_12", id: 'container'} 
        .grid_12
            %div{ class: "grid_2 alpha", id: 'logo'}
                = link_to image_tag("logo.png"), root_path
            %div{ class: "grid_10 omega", id: 'subHeader'}
                - if user_signed_in?
                    = link_to 'Создать новый пик', new_pic_path, class: 'create_pic'  
                    = link_to 'Мои пики', userpics_path(current_user), class: 'menu' 
                    = link_to 'Выйти', sign_out_path, class: 'menu'                   
                -else
                    Войти через 
                    = link_to "Вконтакте", user_omniauth_authorize_path(:vkontakte), class: 'vk' 
                    или
                    = link_to "Facebook", user_omniauth_authorize_path(:facebook) , class: 'fb'

app/views/layouts/_sidebar.html.haml
%div{id: "sidebar", class: "grid_4"}
  .sidebarSection
    %h1 Пик онлайн на Thinkpic
    %p
      - unless user_signed_in?
        Thinkpic позволит тебе создавать и коллекционировать мысли в картинках.
        %br
        Теперь твои мысли в надежном месте.
        %br
        %br
      Для вашей безопасности, на главной странице находятся пики с рейтингом
      %b +5
      %br
      = link_to 'Смотреть все пики', list_pics_path

    %p
      Пиков в базе:
      = Pic.count
      %br
      Собрано лайков:
      = Like.count
  = render partial: "layouts/social"

app/views/layouts/_social.html.erb
<script type="text/javascript" src="//vk.com/js/api/openapi.js?79"></script>

<!-- VK Widget -->
<div id="vk_groups" style="margin-left:10px;"></div>
<script type="text/javascript">
VK.Widgets.Group("vk_groups", {mode: 1, width: "300", height: "290"}, 45863739);
</script>

app/views/layouts/application.html.haml
!!! 5
%html

  %head
    %title ThinkPic
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tag
    %link{:href => "http://fonts.googleapis.com/css?family=PT+Sans:400,700&subset=latin,cyrillic", :rel => "stylesheet", :type => "text/css"}
    %link{:href => "http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/blitzer/jquery-ui.css", :rel => "stylesheet", :type => "text/css"}

  %body

    = render :partial => "layouts/header"
    %div{ id: "container", class: "container_12"}
      = render :partial => "layouts/content"
      = render :partial => "layouts/sidebar"
    .clear  
    = render :partial => "layouts/footer"
      
      
        
      
    

app/views/pics/_pic.html.haml
%div{class: :pic, id: "pic_#{pic.id}", style: "background-image: url(\"#{pic.pic_style.bg.url}\")"}
    .main_text{style: "color: #{pic.pic_style.main_color}"}
        =raw pic.main
    .bold_text{style: "color: #{pic.pic_style.bold_color}"}
        =raw pic.bold
%img{src:'', id:"pic#{pic.id}", style: 'display: none;', title: "Пик #{pic.id}"}
.pic_info
    %center
        .count
            - if (pic.likes.where(user_id: current_user)).size > 0
                = link_to "&#10084;".html_safe, likeit_path(pic), id: "like#{pic.id}",  class: 'heart active', remote: true, onclick: "$('#like#{pic.id}').toggleClass('active');"
            -else
                = link_to "&#10084;".html_safe, likeit_path(pic), id: "like#{pic.id}", class: 'heart', remote: true, onclick: "$('#like#{pic.id}').toggleClass('active');"
            %span{id: "like#{pic.id}Count"}
                = pic.likes.count
    %hr
    %center= link_to_function "Получить пик картинкой", "html2canvas($(\"#pic_#{pic.id}\"), {onrendered: function(canvas) { var img = canvas.toDataURL(); $('#pic#{pic.id}').attr('src', img ).dialog({ height: 330, width: 500, modal: true });  }});", class: 'user_name'
    %hr
    = render partial: "tag", collection: pic.tag_list
    %br
    %br
    %center
        -if pic.user==current_user
            %center= link_to "&#8999; Удалить".html_safe, pic_path(pic), method: :delete, class: 'tag'



app/views/pics/_tag.html.haml
= link_to "&#8998; #{tag}".html_safe, tag_path(tag), class: 'tag' 

app/views/pics/index.html.haml
= render partial: 'pics/pic', collection: @pics
.clear

.flickr_pagination
  = will_paginate @pics, next_label: 'Вперед', previous_label: 'Назад'

app/views/pics/likeit.js.erb
$("<%= "#like#{@pic.id}Count" %>").html(<%=@pic.likes.count%>);

app/views/pics/list.html.haml
= render partial: 'pics/pic', collection: @pics
.clear

.flickr_pagination
  = will_paginate @pics, next_label: 'Вперед', previous_label: 'Назад'

app/views/pics/new.html.haml
%h3 Ну давай, #{current_user.username}!
Для того чтобы создать пик, просто кликай и редактируй надписи "Текст 1" и "Текст 2". После создания твой пик будет хранится в разделе "Мои пики" и попадет в общую ленту.
%br
Редактировать пики нельзя, поэтому следи за написанием, а если что-то не получилось, то всегда можно нажать кнопку "Удалить".
%br
В социальные сети проще публиковать картинку, для этого нажми на клавишу "Получить пик".
%br
%br
Помни наши правила:
%li мы любим русский язык;
%li мы не используем копи-паст;
%li мы заботимся о чистоте нашего сообщества;
%li мы используем теги, но не более 5 к пику.
%br
%br
.clear
.pic{style: "background-image: url(#{PicStyle.first.bg.url})"}
    .main_text{style: "color:#{PicStyle.first.main_color}"}
        #text_prev{contenteditable: true, onpaste: "return false;"} <br><br><br>Текст 1
    .bold_text{style: "color:#{PicStyle.first.bold_color}"}
        #text_prev_bold{contenteditable: true, onpaste: "return false;"} Текст 2


.clear



%p
Теги разделяются клавишей
%b TAB



= form_for @pic, {:url => pics_path, :html => { :multipart => true }} do |f|
    =hidden_field_tag "pic[main]", "Текст 1"
    =hidden_field_tag "pic[bold]", "Текст 2"
    =#for rmagick hidden_field_tag :bold_offset, "103"
    %ul#picTags
    Стиль:
    =f.select :pic_style_id, PicStyle.all.map{|x| [x.name, x.id]}
    %br
    %br

    =submit_tag "Создать пик", id: "create_pic"

app/views/pics/pics_by_tags.html.haml
%h1 
	Поиск по тегу:
	= params[:tag]
= render partial: 'pics/pic', collection: @pics
.clear

.flickr_pagination= will_paginate @pics, next_label: 'Вперед', previous_label: 'Назад'

app/views/pics/show.html.haml
= render partial: 'pics/pic', collection: @pic

app/views/pics/userpics.html.haml
%h1
  Пики пользователя:
  = @user.username
= render partial: 'pics/pic', collection: @pics

.flickr_pagination= will_paginate @pics, next_label: 'Вперед', previous_label: 'Назад'